export const storeProducts  = [
   {
    id: 1,
    name: 'I Phone 12 pro max',
    price: '100',
    like: false,
    inCart:false,
    count: 0,
    total:0,
    img: 'assets/images/product-4.jpg',
     },
    {
      id: 2,
      name: 'Washing Machine',
      price: '70',
      like: false,
      inCart:false,
      count: 0,
      total:0,
      img: 'assets/images/product-3.png',
       },
    {
      id: 3,
      name: 'LCD TV - Black',
      price: '80',
      like: false,
      inCart:false,
      count: 0,
      total:0,
      img: 'assets/images/product-6.png',
      },
      {
        id: 4,
        name: 'LG Refrigerator',
        price: '75',
        like: false,
        inCart:false,
        count: 0,
        total:0,
        img: 'assets/images/product-5.png',
        },
        {
          id: 5,
          name: 'Microwave Oven',
          price: '50',
          like: false,
          inCart:false,
          count: 0,
          total:0,
          img: 'assets/images/product-7.jpg',
          },
          {
            id: 6,
            name: 'One Plus 8 - Blue',
            price: '65',
            like: false,
            inCart:false,
            count: 0,
            total:0,
            img: 'assets/images/product-2.jpg',
            },
       {
      id: 7,
      name: 'Computer',
      price: '40',
      like: true,
      inCart:false,
      count: 0,
      total:0,
      img: 'assets/images/product-8.png',
     },
    {
      id: 8,
      name: 'Solar',
      price: '55',
      like: true,
      inCart: false,
      count: 0,
      total:0,
      img: 'assets/images/product-9.png',
      },
      {
        id: 9,
        name: 'Redmi note 10',
        price: '40',
        like: true,
        inCart: false,
        count: 0,
        total:0,
        img: 'assets/images/product-1.jpg',
        },

  ];
 